"""
core/hopfield.py — Continuous Hopfield Working Memory

Implements the energy-minimising associative memory used as the
spatial reasoning scratchpad. Mathematical basis: §3.6, §3.6.1.

Key insight: Each Hopfield step R_{τ+1} = softmax(β R_τ M_K^T) M_V
monotonically decreases the energy landscape. After H=3 iterations
the state has converged close enough to a stored rule prototype.

D4-invariant version averages results over all 8 symmetry transforms
so the working memory is blind to rotations/reflections of the grid.
"""

import jax
import jax.numpy as jnp
from jax import Array


# ---------------------------------------------------------------------------
# Single Hopfield retrieval step
# ---------------------------------------------------------------------------

def hopfield_step(R: Array, M_K: Array, M_V: Array, beta: float = 0.1) -> Array:
    """
    One Hopfield memory retrieval step.

    R_{τ+1} = softmax(β · R_τ · M_K^T) · M_V

    Args:
        R:   Float[Array, "... D"]  — current register state
        M_K: Float[Array, "K D"]   — stored rule keys   (K slots)
        M_V: Float[Array, "K D"]   — stored rule values (K slots)
        beta: float                 — inverse temperature

    Returns:
        Float[Array, "... D"] — updated register state
    """
    # Attention scores: (..., D) @ (D, K) → (..., K)
    scores = beta * (R @ M_K.T)
    attention = jax.nn.softmax(scores, axis=-1)   # (..., K)
    # Retrieve: (..., K) @ (K, D) → (..., D)
    return attention @ M_V


def hopfield_refinement(R_init: Array, M_K: Array, M_V: Array,
                        beta: float = 0.1, H: int = 3) -> Array:
    """
    Iterative Hopfield refinement toward energy minimum.

    Uses jax.lax.fori_loop so XLA can optimise the fixed-count loop.

    Args:
        R_init: Float[Array, "... D"] — starting register
        M_K:    Float[Array, "K D"]
        M_V:    Float[Array, "K D"]
        beta:   float
        H:      int — number of refinement steps

    Returns:
        Float[Array, "... D"] — refined register at equilibrium
    """
    def step(_, R):
        return hopfield_step(R, M_K, M_V, beta)

    return jax.lax.fori_loop(0, H, step, R_init)


# ---------------------------------------------------------------------------
# D4 symmetry transforms (operate on the last two spatial dimensions
# when R is interpreted as (..., H, W, d_feat) or on a flat token dim
# if we treat the 2D structure implicitly via coordinate encoding).
#
# For Phase 2 we operate on the full D-dim state vector per token and
# apply spatial transforms on the (seq_len,) token ordering. The caller
# is responsible for re-folding/unfolding grid → tokens as needed.
# ---------------------------------------------------------------------------

def _identity(x):          return x
def _rot90(x):             return jnp.rot90(x, k=1, axes=(0, 1))
def _rot180(x):            return jnp.rot90(x, k=2, axes=(0, 1))
def _rot270(x):            return jnp.rot90(x, k=3, axes=(0, 1))
def _flip_h(x):            return jnp.flip(x, axis=1)   # flip columns
def _flip_v(x):            return jnp.flip(x, axis=0)   # flip rows
def _transpose(x):         return jnp.swapaxes(x, 0, 1)
def _antidiag(x):          return jnp.swapaxes(jnp.flip(jnp.flip(x, axis=0), axis=1), 0, 1)

# The D4 group is generated by rot90 and flip_h.
# Inverses: identity⁻¹=identity, rot90⁻¹=rot270, rot180⁻¹=rot180,
#           rot270⁻¹=rot90, flip_h⁻¹=flip_h, flip_v⁻¹=flip_v,
#           transpose⁻¹=transpose, antidiag⁻¹=antidiag.
_D4_FORWARD = [_identity, _rot90,  _rot180, _rot270,
               _flip_h,   _flip_v, _transpose, _antidiag]
_D4_INVERSE = [_identity, _rot270, _rot180, _rot90,
               _flip_h,   _flip_v, _transpose, _antidiag]


def d4_invariant_hopfield(
    R_init: Array,     # Float["H W D"] — 2D grid of state vectors
    M_K: Array,        # Float["K D"]
    M_V: Array,        # Float["K D"]
    beta: float = 0.1,
    H: int = 3,
) -> Array:
    """
    D4-symmetric Hopfield update — invariant to grid rotations/reflections.

    For each of the 8 dihedral transforms g ∈ D4:
      1. Apply transform T_g to the spatial dims of R
      2. Run H steps of Hopfield refinement
      3. Apply inverse T_g^{-1} to bring back to canonical orientation
    Average over all 8 results.

    Args:
        R_init: Float[Array, "H W D"] — spatial grid of state vectors
        M_K:    Float[Array, "K D"]
        M_V:    Float[Array, "K D"]
        beta:   float
        H:      int

    Returns:
        Float[Array, "H W D"] — D4-invariant refined state
    """
    result = jnp.zeros_like(R_init)

    for T, T_inv in zip(_D4_FORWARD, _D4_INVERSE):
        R_transformed = T(R_init)                               # spatial transform
        R_refined = hopfield_refinement(R_transformed, M_K, M_V, beta, H)
        result = result + T_inv(R_refined)                      # inverse transform

    return result / 8.0   # average over group


def hopfield_flat(
    R_flat: Array,     # Float["S D"] — flat token sequence
    M_K: Array,
    M_V: Array,
    beta: float = 0.1,
    H: int = 3,
) -> Array:
    """
    Non-spatial Hopfield refinement on a flat token sequence.
    Used when the caller has already handled spatial structure via
    phase encoding (no need to track 2D layout inside Hopfield).

    Args:
        R_flat: Float[Array, "S D"]
        M_K:    Float[Array, "K D"]
        M_V:    Float[Array, "K D"]
        beta, H: as above

    Returns:
        Float[Array, "S D"]
    """
    return hopfield_refinement(R_flat, M_K, M_V, beta, H)


def hopfield_flat_batched(
    R_batch: Array,    # Float["B S D"]
    M_K: Array,
    M_V: Array,
    beta: float = 0.1,
    H: int = 3,
) -> Array:
    """Batched flat Hopfield — vmaps over batch dimension."""
    return jax.vmap(lambda R: hopfield_flat(R, M_K, M_V, beta, H))(R_batch)


# ---------------------------------------------------------------------------
# Initialisation
# ---------------------------------------------------------------------------

def init_hopfield_params(key: Array, K: int, D: int):
    """
    Initialise Hopfield memory matrices.

    Args:
        key: JAX PRNG key
        K: Number of memory slots
        D: Feature dimension

    Returns:
        dict: {"M_K": Array[K, D], "M_V": Array[K, D]}
    """
    key_k, key_v = jax.random.split(key)
    scale = 1.0 / jnp.sqrt(float(D))
    M_K = jax.random.normal(key_k, (K, D)) * scale
    M_V = jax.random.normal(key_v, (K, D)) * scale
    return {"M_K": M_K, "M_V": M_V}
