"""Continuous Hopfield working memory.

Softmax attention retrieval over stored rule prototypes, iterated toward the
energy minimum. The D4-invariant variant averages over all 8 dihedral
transforms so retrieval is blind to grid rotations and reflections.
"""

import jax
import jax.numpy as jnp
from jax import Array


def hopfield_step(R: Array, M_K: Array, M_V: Array, beta: float = 0.1) -> Array:
    """One retrieval step: R <- softmax(β R M_K^T) M_V."""
    scores = beta * (R @ M_K.T)
    attention = jax.nn.softmax(scores, axis=-1)
    return attention @ M_V


def hopfield_refinement(R_init: Array, M_K: Array, M_V: Array,
                        beta: float = 0.1, H: int = 3) -> Array:
    """H fixed refinement steps toward the energy minimum (fori_loop so XLA
    can optimise the loop)."""
    def step(_, R):
        return hopfield_step(R, M_K, M_V, beta)

    return jax.lax.fori_loop(0, H, step, R_init)


# D4 group: generated by rot90 and flip_h; _D4_INVERSE mirrors _D4_FORWARD.
def _identity(x):          return x
def _rot90(x):             return jnp.rot90(x, k=1, axes=(0, 1))
def _rot180(x):            return jnp.rot90(x, k=2, axes=(0, 1))
def _rot270(x):            return jnp.rot90(x, k=3, axes=(0, 1))
def _flip_h(x):            return jnp.flip(x, axis=1)
def _flip_v(x):            return jnp.flip(x, axis=0)
def _transpose(x):         return jnp.swapaxes(x, 0, 1)
def _antidiag(x):          return jnp.swapaxes(jnp.flip(jnp.flip(x, axis=0), axis=1), 0, 1)

_D4_FORWARD = [_identity, _rot90,  _rot180, _rot270,
               _flip_h,   _flip_v, _transpose, _antidiag]
_D4_INVERSE = [_identity, _rot270, _rot180, _rot90,
               _flip_h,   _flip_v, _transpose, _antidiag]


def d4_invariant_hopfield(
    R_init: Array,
    M_K: Array,
    M_V: Array,
    beta: float = 0.1,
    H: int = 3,
) -> Array:
    """Refine under each D4 transform and average the (inverse-transformed)
    results, so the output is invariant to grid rotations/reflections."""
    result = jnp.zeros_like(R_init)

    for T, T_inv in zip(_D4_FORWARD, _D4_INVERSE):
        R_transformed = T(R_init)
        R_refined = hopfield_refinement(R_transformed, M_K, M_V, beta, H)
        result = result + T_inv(R_refined)

    return result / 8.0


def hopfield_flat(
    R_flat: Array,
    M_K: Array,
    M_V: Array,
    beta: float = 0.1,
    H: int = 3,
) -> Array:
    """Non-spatial refinement on a flat token sequence (caller handles 2D)."""
    return hopfield_refinement(R_flat, M_K, M_V, beta, H)


def hopfield_flat_batched(
    R_batch: Array,
    M_K: Array,
    M_V: Array,
    beta: float = 0.1,
    H: int = 3,
) -> Array:
    """Batched flat Hopfield: vmap over the batch dim."""
    return jax.vmap(lambda R: hopfield_flat(R, M_K, M_V, beta, H))(R_batch)


def init_hopfield_params(key: Array, K: int, D: int):
    """Random memory keys/values, Xavier-scaled."""
    key_k, key_v = jax.random.split(key)
    scale = 1.0 / jnp.sqrt(float(D))
    M_K = jax.random.normal(key_k, (K, D)) * scale
    M_V = jax.random.normal(key_v, (K, D)) * scale
    return {"M_K": M_K, "M_V": M_V}
